---
title: "Untitled"
author: "Kim Antunez et Alain Quartier-la-Tente"
date: "5/12/2020"
output: 
    pdf_document:
        keep_tex: yes
themeoptions: "coding=utf8,language=english"
classoption: 'french'
fontsize: 11pt
geometry: margin=0.95in
lang: "french"
documentclass: "article"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE,
                      fig.height=3,fig.width=8,
  fig.path = "img/rmd-",
  fig.align = "center")
library(ggplot2)
library(AQLTools)
library(zoo)
library(RJDemetra)
library(patchwork)
library(R.utils)
```

```{r}
modeles <- ts(read.csv("../../data_bis/modeles.csv", sep=";")[,-1],
              start = 2011,frequency = 12)
data <- readRDS("../../data_bis/donnes_cam.RDS")
indices_mensuels_baseline <- read.csv("../../data_bis/indices_mensuels_baseline.csv",
                                      sep=";")[,-c(1:2)]
indices_mensuels_baseline <- ts(indices_mensuels_baseline, start = 2011, frequency = 12)
modeles <- ts.union(modeles,indices_mensuels_baseline)
colnames(modeles) <- gsub(".*\\.", "", colnames(modeles))

data[,"Indicateur synthétique"] <- scale(data[,"Indicateur synthétique"] )
data_lag <- lag(data, -1)
ind_retenu <- "reg_log_nrmsw_lf"
donnes_calcul <- scale(ts.intersect(modeles[,c(ind_retenu, "sncf")], data[,1:2]))
donnes_calcul_lag <- scale(ts.intersect(modeles[,c(ind_retenu, "sncf")], data_lag[,1:2]))
colnames(donnes_calcul) <- 
    colnames(donnes_calcul_lag) <- 
    c("Modèle word2vec","Modèle de référence",
      "Indicateur synthétique Camme (Brut)", "Indicateur synthétique Camme (CVS)"
    )

graph_glob <- function(data, titre = NULL, sous_titre = NULL, legende = NULL, afficheVolatilite = FALSE,
                       cex = 0.6, diviserParPeriode = FALSE, x_lab = NULL, x_lab_month = FALSE, y_lab = NULL,
                       outDec = ",",
                       n_xlabel = 8, n_ylabel = 12){
    
    time <- time(data)
    freq <- frequency(data)
    dataGraph <- data.frame(cbind(time, data))
    if (is.null(legende)){
        if(is.mts(data)){
            legende <- colnames(data)
        }else{
            legende <- ""
        }
    }
    colnames(dataGraph) <- c("date", legende)
    
    dataGraph <- reshape2::melt(dataGraph, id="date")  # convert to long format
    
    if (freq==1){
        periode <- "Y"
        periode <- factor(periode)
    }
    if (freq==2){
        periode <- ifelse(time(data)%%1==0, "S1", "S2")
        periode <- factor(periode,levels = c("S1","S2"), ordered = T)
    }
    if (freq==4){
        periode <- capitalize(quarters(zoo::as.yearqtr(dataGraph$date)))
        periode <- factor(periode,levels=capitalize(quarters(zoo::as.yearqtr((0:3)/4))),ordered = T)
    }
    if (freq==12){
        periode <- capitalize(months(zoo::as.yearmon(dataGraph$date)))
        periode <- factor(periode,levels=capitalize(months(zoo::as.yearmon((0:11)/12))),ordered = T)
    }
    
    dataGraph <- data.frame(dataGraph,periode=periode)
    p <- ggplot(data = dataGraph, aes(x = date, y = value, group = variable,
                                      color = variable, linetype = variable,
                                      fill = variable
                                      )) +
        geom_line(size=0.80) +
        labs(title = titre, subtitle = sous_titre,
             x = x_lab, y = y_lab) +
        scale_x_continuous(breaks = scales::pretty_breaks(n = 12),
                           labels = function(x) AQLTools:::creation_x_label(x, x_lab_month = x_lab_month, outDec = outDec)) +
        scale_y_continuous(breaks = scales::pretty_breaks(n = n_ylabel),
                           labels = function(x) format(x, decimal.mark = outDec))+
        AQLTools:::theme_aqltools()
    p
}

graph_cvs <- function(data, titre = NULL, sous_titre = NULL, legende = NULL, afficheVolatilite = FALSE,
                       cex = 0.6, diviserParPeriode = FALSE, x_lab = NULL, x_lab_month = FALSE, y_lab = NULL,
                       outDec = ",",
                       n_xlabel = 8, n_ylabel = 6){
    
    time <- time(data)
    freq <- frequency(data)
    dataGraph <- data.frame(cbind(time, data))
    if (is.null(legende)){
        if(is.mts(data)){
            legende <- colnames(data)
        }else{
            legende <- ""
        }
    }
    colnames(dataGraph) <- c("date", legende)
    
    dataGraph <- reshape2::melt(dataGraph, id="date")  # convert to long format
    
    if (freq==1){
        periode <- "Y"
        periode <- factor(periode)
    }
    if (freq==2){
        periode <- ifelse(time(data)%%1==0, "S1", "S2")
        periode <- factor(periode,levels = c("S1","S2"), ordered = T)
    }
    if (freq==4){
        periode <- capitalize(quarters(zoo::as.yearqtr(dataGraph$date)))
        periode <- factor(periode,levels=capitalize(quarters(zoo::as.yearqtr((0:3)/4))),ordered = T)
    }
    if (freq==12){
        periode <- capitalize(months(zoo::as.yearmon(dataGraph$date)))
        periode <- factor(periode,levels=capitalize(months(zoo::as.yearmon((0:11)/12))),ordered = T)
    }
    
    dataGraph <- data.frame(dataGraph,periode=periode)
    p <- ggplot(data = dataGraph, aes(x = date, y = value, group = variable,
                                      linetype = variable, colour = variable
    ))+
        geom_line(size=0.80) +
        labs(title = titre, subtitle = sous_titre,
             x = x_lab, y = y_lab) +
        scale_x_continuous(breaks = scales::pretty_breaks(n = n_xlabel),
                           labels = function(x) AQLTools:::creation_x_label(x, x_lab_month = x_lab_month, outDec = outDec)) +
        scale_y_continuous(breaks = scales::pretty_breaks(n = n_ylabel),
                           labels = function(x) format(x, decimal.mark = outDec))+
        AQLTools:::theme_aqltools() +
        scale_colour_manual(breaks = colnames(data),
                            values = c( "black", "red"))
    p
}
```


```{r graphSentiments,fig.cap="test"}
data_g <- donnes_calcul_lag[,c(3,1,2)]
colnames(data_g) <-  c("Indicateur synthétique Camme (Brut) retardé",
                       "Modèle word2vec","Modèle de référence")
graph_glob(data_g)   +
    scale_colour_manual(breaks = colnames(data_g),
                        values = c("#D8766D", "#4B0055", "#7ED357"))+
        coord_cartesian(y=c(-3,2.5))+
    guides(color=guide_legend(ncol=3))
```

```{r graphCVS,fig.height=6}

cvs_camme <- graph_cvs(donnes_calcul[,3:4]) +
    theme(legend.position = c(0,1),
          legend.justification = c(0,1)) +
    coord_cartesian(y = c(-2.5,2.5))
cvs_w2vec_ts <- get_indicators(jx13(donnes_calcul[,1]),"y","sa")
cvs_w2vec_ts <- ts.union(cvs_w2vec_ts[[1]], cvs_w2vec_ts[[2]])
colnames(cvs_w2vec_ts) <- paste("Modèle word2vec",c("(Brut)","(CVS)"))
cvs_w2vec <- graph_cvs(cvs_w2vec_ts)  +
    coord_cartesian(y = c(-2.5,2.5))

cvs_baseline_sncf_ts <- get_indicators(jx13(donnes_calcul[,2]),"y","sa")
cvs_baseline_sncf_ts <- ts.union(cvs_baseline_sncf_ts[[1]], cvs_baseline_sncf_ts[[2]])
colnames(cvs_baseline_sncf_ts) <- paste("Modèle de référence",c("(Brut)","(CVS)"))
cvs_baseline_sncf <- graph_cvs(cvs_baseline_sncf_ts)  +
    coord_cartesian(y = c(-2.5,2.5))
cvs_camme / cvs_w2vec / cvs_baseline_sncf
```

```{r graphCoefCVS,fig.height=5}
graph_coefcvs <- function(data, titre = NULL, sous_titre = NULL, legende = NULL, afficheVolatilite = FALSE,
                      cex = 0.6, diviserParPeriode = FALSE, x_lab = NULL, x_lab_month = FALSE, y_lab = NULL,
                      outDec = ",",
                      n_xlabel = 8, n_ylabel = 6){
  
  time <- time(data)
  freq <- frequency(data)
  dataGraph <- data.frame(cbind(time, data))
  if (is.null(legende)){
    if(is.mts(data)){
      legende <- colnames(data)
    }else{
      legende <- ""
    }
  }
  colnames(dataGraph) <- c("date", legende)
  
  dataGraph <- reshape2::melt(dataGraph, id="date")  # convert to long format
  
  if (freq==1){
    periode <- "Y"
    periode <- factor(periode)
  }
  if (freq==2){
    periode <- ifelse(time(data)%%1==0, "S1", "S2")
    periode <- factor(periode,levels = c("S1","S2"), ordered = T)
  }
  if (freq==4){
    periode <- capitalize(quarters(zoo::as.yearqtr(dataGraph$date)))
    periode <- factor(periode,levels=capitalize(quarters(zoo::as.yearqtr((0:3)/4))),ordered = T)
  }
  if (freq==12){
    periode <- capitalize(months(zoo::as.yearmon(dataGraph$date)))
    periode <- factor(periode,levels=capitalize(months(zoo::as.yearmon((0:11)/12))),ordered = T)
  }
  
  dataGraph <- data.frame(dataGraph,periode=periode)
  p <- ggplot(data = dataGraph, aes(x = date, y = value, group = variable, colour = variable
  ))+
    geom_line(size=0.80) +
    labs(title = titre, subtitle = sous_titre,
         x = x_lab, y = y_lab) +
    scale_x_continuous(breaks = scales::pretty_breaks(n = n_xlabel),
                       labels = function(x) substr(x,3,4)) +
    scale_y_continuous(breaks = scales::pretty_breaks(n = n_ylabel),
                       labels = function(x) format(x, decimal.mark = outDec))+
    AQLTools:::theme_aqltools() +
    scale_colour_manual(breaks = colnames(data),
                        values = c("#4B0055", "#7ED357"))
  p
}
coef_sais <- ts.union(get_indicators(jx13(donnes_calcul[,1]),"s")[[1]],
                      get_indicators(jx13(donnes_calcul[,2]),"s")[[1]])
colnames(coef_sais) <- c("Modèle word2vec", "Modèle de référence")
graph_coefcvs(coef_sais,n_xlabel = 4,x_lab = "Dates") +
  geom_hline(yintercept = 0,linetype = "dotted") +
  facet_wrap(~periode,nrow=1)  +
  coord_cartesian(y = c(-.7,.7)) + 
  theme(panel.spacing = unit(0, "lines"))+
  theme(
    legend.justification = "left",
    legend.position = "top"
  )+
  guides(color=guide_legend(nrow=1))
```
